# Generated by Django 2.2.7 on 2019-11-14 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userProfile',
            fields=[
                ('userClass', models.CharField(default='not_null', max_length=30)),
                ('userLogin', models.CharField(default='not_null', max_length=30, primary_key=True, serialize=False)),
                ('userEmail', models.EmailField(default='not_null', max_length=254)),
                ('userPassword', models.CharField(default='not_null', max_length=30)),
            ],
        ),
    ]
