# Generated by Django 2.2.7 on 2019-11-17 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_delete_ecoparameterstandard'),
    ]

    operations = [
        migrations.CreateModel(
            name='ecoParameterMeasured',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecoParamMeasuredValue', models.CharField(max_length=127)),
                ('ecoParamDate', models.DateField()),
                ('ecoParamMeasuredBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userProfile')),
            ],
        ),
        migrations.CreateModel(
            name='ecoParameterStandard',
            fields=[
                ('ecoParamID', models.AutoField(primary_key=True, serialize=False)),
                ('ecoParamName', models.CharField(max_length=127)),
                ('ecoParamValue', models.CharField(max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name='ecoReport',
            fields=[
                ('ecoReportID', models.AutoField(primary_key=True, serialize=False)),
                ('ecoReportParamMsr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eco.ecoParameterMeasured')),
                ('ecoReportParamStd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eco.ecoParameterStandard')),
                ('ecoReportToReview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userProfile')),
            ],
        ),
        migrations.AddField(
            model_name='ecoparametermeasured',
            name='ecoParamMeasuredID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eco.ecoParameterStandard'),
        ),
    ]
