# Generated by Django 2.2.7 on 2019-11-16 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ecoParameterStandard',
            fields=[
                ('ecoParamID', models.AutoField(primary_key=True, serialize=False)),
                ('ecoParamName', models.CharField(max_length=127)),
                ('ecoParamValue', models.CharField(max_length=127)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='userClass',
            field=models.CharField(max_length=30, verbose_name='User class'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='userEmail',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='userLogin',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Login'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='userPassword',
            field=models.CharField(max_length=30, verbose_name='Password'),
        ),
    ]
